version: '3.8'

networks:
  kafka_net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    networks:
      - kafka_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - kafka_net
    depends_on:
      - zookeeper
    ports:
      - "9093:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9093", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - kafka_net
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Creating topics...' &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --topic streams-wordcount-input &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --topic streams-wordcount-output &&
      echo 'Topics created.'
      "
    restart: on-failure
